version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - WEBSITE_DB_HOST=website
      - WEBSITE_DB_NAME=website
      - WEBSITE_DB_USER=vowuser
      - WEBSITE_DB_PASSWORD=password
      - API_DB_HOST=api
      - API_DB_NAME=api
      - API_DB_USER=vowuser
      - API_DB_PASSWORD=password
    volumes:
      - .:/var/www/html
    depends_on:
      - website
      - api
      - adminer

  website:
    image: mariadb:10.5.24
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: website
      MYSQL_USER: vowuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - website_data:/var/lib/mysql

  api:
    image: mariadb:10.5.24
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api
      MYSQL_USER: vowuser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - api_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - website
      - api

volumes:
  website_data:
  api_data:
