version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - website
      - api
      - phpmyadmin

  website:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: website
      MYSQL_USER: vowuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - website_data:/var/lib/mysql

  api:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: api
      MYSQL_USER: vowuser
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - api_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: website
      PMA_PORT: 3306
      PMA_USER: vowuser
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - website
      - api

volumes:
  website_data:
  api_data:

